name: ${modId}
version: ${modVersion}
author: ${modAuthor}
description: ${modDescription}
website: ${websiteUrl}

main: "net.axay.levelborder.paper.LevelBorderPlugin"

api-version: ${minecraftVersion}
