modLoader = "javafml"
loaderVersion = "[39,)"
license = "GNU General Public License v3.0"

[[mods]]
modId = "${modId}"
version = "${modVersion}"
displayName = "${modName}"
logoFile = "examplemod.png"
authors = "${modAuthor}"
description = "${modDescription}"
