modLoader = "javafml"
loaderVersion = "[39,)"
license = "${modLicense}"

[[mods]]
modId = "levelborder"
version = "${modVersion}"
displayName = "${modName}"
logoFile = "examplemod.png"
authors = "${modAuthor}"
description = "${modDescription}"
